# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
library(vetiverTest)
b <- board_connect(auth = "envvar")
v <- vetiver_pin_read(b, "hannar1/my_model", version = "484898")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
